version: "3.8"

services:
  backend:
    build: ./backend/
    environment:
      - ADDR=0.0.0.0
      - PORT=8080
      - NODE_ENV=development
      - API_KEY=${API_KEY}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    ports:
      - "8080:8080"
    restart: unless-stopped